# Generated by Django 5.0.1 on 2025-04-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_hospital_number_alter_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedication',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
