# Generated by Django 5.0.1 on 2025-04-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientmedication_next_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
